name: Packer Template Check

on:
  pull_request:
    branches:
      - main

jobs:
  packer-check:
    runs-on: ubuntu-24.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Packer
        uses: hashicorp/setup-packer@v3
        with:
          packer_version: latest

      - name: Run packet init
        run:
          packer init ./packer/aws.pkr.hcl

      - name: Run packer fmt
        id: packer_fmt
        run: |
          packer fmt -diff ./packer/aws.pkr.hcl
          git diff --exit-code

        continue-on-error: false
      
      - name: Run packer validate
        id: packer_validate
        run: |
          packer validate --syntax-only ./packer/aws.pkr.hcl
        
        continue-on-error: false
