name: Build Packer custom image

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  build_and_test:
    name: Build and upload jar file then create custom AMI
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-24.04

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'
          architecture: x64

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run tests
        env: 
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: ./gradlew test

      - name: Build jar file
        run: ./gradlew clean build

      - name: Install Packer on Ubuntu
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install -y packer

      - name: Configure AWS Credentials Action for GitHub Actions
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: $AWS_ACCESS_KEY
          aws-secret-access-key: $AWS_SECRET_ACCESS_KEY
          aws-region: $AWS_REGION

      - name: Initialize Packer
        run: |
          packer init ./packer/aws.pkr.hcl

      - name: Build Custom Image
        run: |
          packer build \
            -var "aws_region=$AWS_REGION" \
            -var "access_key=$AWS_ACCESS_KEY" \
            -var "secret_key=$AWS_SECRET_ACCESS_KEY" ./packer/aws.pkr.hcl 


            
