name: Packer Template Check

# This workflow runs on pull request events
on:
  pull_request:
    branches:
      - main

jobs:
  packer-check:
    runs-on: ubuntu-24.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Install Packer
      - name: Install Packer
        uses: hashicorp/setup-packer@v3
        with:
          packer_version: latest

      # Step 3: Run packer fmt and check for changes
      - name: Run packer fmt
        id: packer_fmt
        run: |
          packer fmt -diff ./packer/aws.pkr.hcl
          git diff --exit-code

        # If packer fmt modified any files, the workflow will fail
        continue-on-error: false
      
      # Step 4: Run packer validate
      - name: Run packer validate
        id: packer_validate
        run: |
          packer validate ./packer/aws.pkr.hcl
        
        # If packer validate fails, the workflow will also fail
        continue-on-error: false
